export const SA_UNIVERSITIES = [
  "Cape Peninsula University of Technology (CPUT)",
  "Central University of Technology (CUT)",
  "Durban University of Technology (DUT)",
  "Mangosuthu University of Technology (MUT)",
  "Nelson Mandela University (NMU)",
  "North-West University (NWU)",
  "Rhodes University",
  "Sefako Makgatho Health Sciences University (SMU)",
  "Sol Plaatje University (SPU)",
  "Stellenbosch University",
  "Tshwane University of Technology (TUT)",
  "University of Cape Town (UCT)",
  "University of Fort Hare",
  "University of the Free State (UFS)",
  "University of Johannesburg (UJ)",
  "University of KwaZulu-Natal (UKZN)",
  "University of Limpopo",
  "University of Mpumalanga (UMP)",
  "University of Pretoria (UP)",
  "University of South Africa (UNISA)",
  "University of Venda (Univen)",
  "University of the Western Cape (UWC)",
  "University of the Witwatersrand (Wits)",
  "University of Zululand (UniZulu)",
  "Vaal University of Technology (VUT)",
  "Walter Sisulu University (WSU)",
  "Other (Private College/Manual)"
];

export const SA_FACULTIES = {
  "Business, Commerce & Management": [
    "College of Accounting Sciences",
    "College of Business and Economics",
    "College of Economic and Management Sciences",
    "College of Law and Management Studies",
    "Faculty of Commerce",
    "Faculty of Commerce, Law and Management",
    "Faculty of Economic and Management Sciences",
    "Faculty of Economics and Finance",
    "Faculty of Management Sciences",
    "Faculty of Management, Commerce and Law",
    "Faculty of Business and Management Sciences",
    "Gordon Institute of Business Science (GIBS)",
    "Graduate School of Business Leadership",
    "Tshwane School for Business and Society"
  ],
  "Engineering, Science & Technology": [
    "College of Agriculture and Environmental Sciences",
    "College of Agriculture, Engineering and Science",
    "College of Science, Engineering and Technology",
    "Faculty of AgriSciences",
    "Faculty of Agriculture and Natural Sciences",
    "Faculty of Science",
    "Faculty of Engineering",
    "Faculty of Engineering and the Built Environment",
    "Faculty of Engineering, Built Environment and Information Technology",
    "Faculty of Engineering and Infrastructure",
    "Faculty of Engineering and Information Technology",
    "Faculty of Natural and Agricultural Sciences",
    "Faculty of Natural and Applied Sciences",
    "Faculty of Information and Communication Technology",
    "Faculty of Informatics and Design",
    "Faculty of Science, Agriculture and Engineering",
    "Faculty of Science and Agriculture",
    "Faculty of Science, Engineering and Agriculture",
    "School of Science & Technology"
  ],
  "Health, Medicine & Veterinary Care": [
    "College of Health Sciences",
    "Faculty of Health Sciences",
    "Faculty of Medicine and Health Sciences",
    "Faculty of Veterinary Science",
    "School of Medicine",
    "School of Oral Health Sciences / Dentistry",
    "School of Pharmacy",
    "School of Health Care Sciences"
  ],
  "Humanities, Education & Social Sciences": [
    "College of Graduate Studies",
    "College of Human Sciences",
    "Faculty of Art, Design and Architecture",
    "Faculty of Arts and Design",
    "Faculty of Arts and Humanities",
    "Faculty of Arts",
    "Faculty of Arts and Social Sciences",
    "Faculty of Military Science",
    "Faculty of Education",
    "Faculty of Education and Social Sciences",
    "Faculty of Humanities",
    "Faculty of Humanities, Social Sciences and Education",
    "Faculty of Social Sciences and Humanities",
    "Faculty of Theology and Religion",
    "Faculty of Theology"
  ],
  "Law": [
    "College of Law",
    "Faculty of Law"
  ]
};
